# Generated by Django 4.2.7 on 2024-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastProject', '0005_question_choice_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
